import React from 'react'
import { render } from 'react-dom' // eslint-disable-line no-unused-vars

import Logo from './Logo'

class Footer extends React.Component {
  render () {
    return (
      <footer className='c-Footer'>
        <div className='c-Footer__inner'>
          <a href='https://speedtracker.org' className='c-Footer__logo'>
            <Logo width={40} />
          </a>

          <p>Report generated by <a href='https://speedtracker.org'>SpeedTracker</a>. Data captured using <a href='https://www.webpagetest.org/'>WebPageTest</a>.</p>
          <p>Setup by Jan-Willem Bobbink <a href='http://www.notprovided.eu'>Notprovided.eu</a></p>

         
        </div>
      </footer>
    )
  }
}

export default Footer
